baseurl = "http://houzet.info"
title = "Houzet"

theme = "hugo-coder"

languagecode = "fr"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Sébastien Houzet"
    description = "Bienvenue sur Houzet.info"
    keywords = "blog,developer,personal,houzet"
    info = "Consultant IT"
    avatarurl = "images/houzet.jpg"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = false

    rtl = false

    # Use inverted colors
    inverted = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/sebastienhouzet/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/sebastienhouzet/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://fr.linkedin.com/in/sebastienhouzet"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@sebastien.houzet"


[[menu.main]]
name = "About"
weight = 1
url = "https://sebastien.houzet.info"
